name: 'Container Action Template'
description: 'Get started with Container actions'
author: 'GitHub'
inputs: 
  token:
    description: 'Kebechet GitHub API token'
    default: '{{ secrets.GITHUB_TOKEN }}'
    required: true
  configuration_path:
    description: 'Path to the Kebechet configuration file'
    default: './thoth.yaml'
    required: true
  verbose:
    description: 'Whether Kebechet should run in verbose mode'
    default: '1'
    required: false
runs:
  using: 'docker'
  image: '../Dockerfile'
  env:
    # Default configuration
    KEBECHET_REPO_URL: 'https://{{ GITHUB_REPOSITORY }}/{{ GITHUB_REF }}'
    KEBECHET_SUBCOMMAND: 'run'
    # Credentials
    KEBECHET_TOKEN: '{{ inputs.token }}'
    # Additional configuration
    KEBECHET_CONFIGURATION_PATH: '{{ inputs.configuration_path }}'
    KEBECHET_VERBOSE: '{{ inputs.verbose }}'
