language: python
python:
- '3.6'
script: true
deploy:
  provider: pypi
  user: fridex
  password:
    secure: ayHzcLmxkglaUTgaiLH//t9oS/VMSlE/k+JUK3ITdIsG4EdQxw6S7zM2bOBghGZmQ+XuK4tE6NvNdOXr3xhNfEBnEz9aXFidvJfLU8c4yR4ZMXbuftgNb/8sZy0eeLQoGYPBHXP0m0d/S5ikx9+0HOFY1rdZfsCIplUb536lBomZc+naPBOMzhA2QUOgSJT4ucICcSMdZ75IRMokGSIytborrDJ2EQuLDSQUvS+X0umN6TB8gMJxiTAu+II+RBqneGd1VvTq+PQ/JywNNVxVsC25H/hKvR+iPlxeaT01qSxtiPONuW5YitXZW2FME8Jb07PIAJd8rV+1HOJVpHqNAiiAIOzgHILYHOIPgnMo6QX5GKO3q9jEQ3gwy9zJInRLWYfqyBWDsCm5NjPHsvg2gVe2lvua570MzCMOoXh7aAqYchSLOmYI+tHUntqmH6q6M5dn4D0VvRFv4MENqOJcWFe86FhBPTGy2toDMA4ra5+7I73xgmgTf/p+q9Fwf1SK1Wyl9vQ/lmR07+nmRlfPd3zX14PdozkYcXynz8BqZ6FEYuQEoLEgqoAhef6wT7fBwiq0xiNT7K6V0vvSZ3L+n61yXjBdq9sY2dWB79ezNU5k/FhDt4dMQ3Vl/KK7U6J9nKzblQcKFU55yn85QmOOXzuax3Hw81R4M1G9V3AE1vk=
  on:
    tags: true
    branch: master
  distributions: sdist bdist_wheel
