- project:
    check:
      jobs:
        - linters:
            vars:
              linters:
                - coala
    gate:
      jobs:
        - linters:
            vars:
              linters:
                - coala

    post:
      jobs:
        - trigger-build:
            vars:
              webhook_url: "https://url.corp.redhat.com/aicoe-prod-bots-kebechet-job-build-trigger"

    release:
      jobs:
        - upload-pypi-sesheta

    kebechet-auto-gate:
      jobs:
        - linters:
            vars:
              linters:
                - coala