- project:
    check:
      jobs:
        - linters:
            vars:
              linters:
                - coala
    gate:
      jobs:
        - linters

    release:
      jobs:
        - upload-test-pypi

    sesheta-auto-gate:
      jobs:
        - linters:
            vars:
              linters:
                - coala
