- project:
    check:
      jobs:
        - "thoth-coala"
    gate:
      jobs:
        - "thoth-coala"
    post:
      jobs:
        - trigger-build:
            vars:
              webhook_url: "https://paas.upshift.redhat.com/oapi/v1/namespaces/aicoe-prod-bots/buildconfigs/kebechet-job"
    release:
      jobs:
        - "upload-pypi-sesheta"
    kebechet-auto-gate:
      jobs:
        - "thoth-coala"
