---
repositories:
  - slug: CermakM/jupyter-datatables
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: info
        configuration:
          labels: [bot]
      - name: version
        configuration:
          maintainers:
            - CermakM
          assignees:
            - CermakM
          changelog_file: true

  - slug: CermakM/jupyter-require
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: info
        configuration:
          labels: [bot]
      - name: version
        configuration:
          maintainers:
            - CermakM
          assignees:
            - CermakM
          changelog_file: true
