---
update:
  - slug: thoth-station/adviser
    label: ['approved', 'bot']
  - slug: thoth-station/analyzer
    label: ['approved', 'bot']
  - slug: thoth-station/cleanup-job
    label: ['approved', 'bot']
  - slug: thoth-station/common
    label: ['approved', 'bot']
  - slug: thoth-station/graph-refresh-job
    label: ['approved', 'bot']
  - slug: thoth-station/graph-sync-job
    label: ['approved', 'bot']
  - slug: thoth-station/lab
    label: ['approved', 'bot']
  - slug: thoth-station/package-extract
    label: ['approved', 'bot']
  - slug: thoth-station/package-releases-job
    label: ['approved', 'bot']
  - slug: thoth-station/result-api
    label: ['approved', 'bot']
  - slug: thoth-station/solver
    label: ['approved', 'bot']
  - slug: thoth-station/storages
    label: ['approved', 'bot']
  - slug: thoth-station/user-api
    label: ['approved', 'bot']
  - slug: thoth-station/kebechet
    label: ['approved', 'bot']
