---
repositories:
  - slug: thoth-station/adviser
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/analyzer
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/cleanup-job
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/common
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/graph-refresh-job
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/graph-sync-job
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/lab
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/package-extract
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/package-releathamosses-job
    token: '{KEBECHET_TOKEN}'thamos
    managers:thamos
      - name: updatethamos
        configuration:thamos
          labels: [bot]thamos
      - name: infothamos
      - name: versionthamos
        configuration:thamos
          maintainers:thamos
            - goernthamos
            - fridexthamos
          assignees:thamos
            - seshetathamos
          labels: [bot]thamos
          changelog_file: truethamos

  - slug: thoth-station/result-api
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/solver
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/storages
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/user-api
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/kebechet
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/jupyter-notebook
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: thoth-station/sesheta
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]

  - slug: thoth-station/srcops-testing
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]

  - slug: thoth-station/cve-update-job
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: [bot]
      - name: info

  - slug: thoth-station/thamos
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: pipfile-requirements
      - name: update
        configuration:
          labels: [bot]
      - name: info
      - name: version
        configuration:
          maintainers:
            - goern
            - fridex
          assignees:
            - sesheta
          labels: [bot]
          changelog_file: true

  - slug: user-cont/conu
    token: '{KEBECHET_TOKEN}'
    managers:
      - name: update
        configuration:
          labels: 
            - bot
            - thoth-station
            - kebechet
