apiVersion: v1
kind: Template
labels:
  template: kebechet-buildconfig
  thoth: 0.1.0
metadata:
  name: kebechet-buildconfig
  annotations:
    description: This is Kebechet CronJob BuildConfig, this template is meant to be used by Jenkins, but could also be used by humans...
    openshift.io/display-name: Kebechet BuildConfig
    version: 0.2.0
    tags: poc,thoth,ai-stacks,kebechet
    template.openshift.io/documentation-url: https://github.com/AICoE/Thoth/
    template.openshift.io/long-description: This is Kebechet used for automatic package releases and updates.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: kebechet
    name: kebechet-job
  spec:
    resources:
      requests:
        memory: "1000Mi"
        cpu: "1000m"
      limits:
        memory: "1000Mi"
        cpu: "1000m"
    output:
      to:
        kind: ImageStreamTag
        name: "kebechet-job:${IMAGE_STREAM_TAG}"
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: ${GITHUB_URL}
        ref: ${GITHUB_REF}
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile
    triggers:
    - imageChange: {}
      type: ImageChange

parameters:
- description: Git repository for Thoth's Kebechet
  displayName: Thoth Kebechet git repository
  required: true
  name: GITHUB_URL
  value: 'https://github.com/thoth-station/kebechet'

- description: Git repository for Thoth's Graph Sync Job
  displayName: Thoth Kebechet git reference
  required: true
  name: GITHUB_REF
  value: 'master'

- description: Tag of the output ImageStream the resulting container image should go to
  displayName: ImageStream Tag
  required: true
  name: IMAGE_STREAM_TAG
  value: 'latest'
