apiVersion: v1
kind: ConfigMap
metadata:
  name: kebechet-configmap
  labels:
    app: kebechet
annotations:
  description: This is Kebechet ConfigMap, this template is meant to be used by Jenkins, but could also be used by humans...
  openshift.io/display-name: Kebechet ConfigMap
  version: 0.2.0
  tags: poc,thoth,ai-stacks,kebechet
  template.openshift.io/documentation-url: https://github.com/AICoE/Thoth/
  template.openshift.io/long-description: This is Kebechet used for automatic package releases and updates.
  template.openshift.io/provider-display-name: Red Hat, Inc.
data:
  kebechet-config: ${KEBECHET_CONFIGURATION}
  kebechet-verbose: ${KEBECHET_VERBOSE}

parameters:
  - description: Kebechet configuration file.
    displayName: Kebechet configuration
    required: true
    name: KEBECHET_CONFIGURATION
    
  - description: Kebechet verbose mode.
    displayName: Kebechet Verbose
    required: true
    name: KEBECHET_VERBOSE
    value: "1"
