apiVersion: v1
kind: Template
labels:
  template: kebechet-configmap
  thoth: 0.1.0
metadata:
  name: configmap-configmap
  annotations:
    description: This is Kebechet ConfigMap, this template is meant to be used by Jenkins, but could also be used by humans...
    openshift.io/display-name: Kebechet ConfigMap
    version: 0.2.0
    tags: poc,thoth,ai-stacks,kebechet
    template.openshift.io/documentation-url: https://github.com/AICoE/Thoth/
    template.openshift.io/long-description: This is Kebechet used for automatic package releases and updates.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: kebechet
    labels:
      app: kebechet
  data:
    github-oauth-token: ${GITHUB_OAUTH_TOKEN}
    kebechet-config: ${KEBECHET_CONFIG}

parameters:
- description: GitHub OAuth token used for authentication.
  displayName: GitHub Oauth token
  required: true
  name: GITHUB_OAUTH_TOKEN

- description: Kebechet configuration file.
  displayName: Kebechet configuration
  required: true
  name: KEBECHET_CONFIG

# TODO: add keys
