apiVersion: v1
kind: Template
metadata:
  name: kebechet-imagestream
  annotations:
    description: This is Kebechet ImageStream, this template is meant to be used by Bots, but could also be used by humans...
    openshift.io/display-name: Kebechet ImageStream
    version: 1.0.0
    tags: poc,thoth,ai-stacks,kebechet
    template.openshift.io/documentation-url: https://github.com/thoth-station/kebechet/
    template.openshift.io/long-description: This is Kebechet used for automatic package releases and updates.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: kebechet-imagestream
    app: kebechet

objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: kebechet
    name: kebechet-job
  spec:
    name: latest
    lookupPolicy:
      local: true

