apiVersion: v1
kind: Secret
metadata:
  name: kebechet-secret
  labels:
    app: kebechet
stringData:
  ssh-privatekey: ${KEBECHET_SSH_PRIVATE_KEY}
  github-oauth-token: ${KEBECHET_TOKEN}
annotations:
  description: This is Kebechet Secrets - This template is build for all the secrets that are required to deploy Kebechet.
  openshift.io/display-name: Kebechet Secrets
  version: 0.1.0
  tags: poc,thoth,ai-stacks,kebechet
  template.openshift.io/documentation-url: https://github.com/AICoE/Thoth/
  template.openshift.io/long-description: This is Kebechet used for automatic package releases and updates.
  template.openshift.io/provider-display-name: Red Hat, Inc.

parameters:
  - description: SSH private key to authenticate the public key set in GitHub.
    displayName: SSH Private Key
    required: true
    name: KEBECHET_SSH_PRIVATE_KEY
  
  - description: GitHub OAuth token used for authentication.
    displayName: GitHub Oauth token
    required: true
    name: KEBECHET_TOKEN
