apiVersion: v1
kind: Template
labels:
  template: kebechet-imagestream
  thoth: 0.1.0
metadata:
  name: kebechet-imagestream
  annotations:
    description: This is Kebechet ImageStream, this template is meant to be used by Bots, but could also be used by humans...
    openshift.io/display-name: Kebechet ImageStream
    version: 1.0.0
    tags: poc,thoth,ai-stacks,kebechet
    template.openshift.io/documentation-url: https://github.com/thoth-station/kebechet/
    template.openshift.io/long-description: This is Kebechet used for automatic package releases and updates.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: kebechet-secret
    labels:
      app: kebechet
  stringData:
    ssh-privatekey: ${KEBECHET_SSH_PRIVATE_KEY}
    github-oauth-token: ${KEBECHET_TOKEN}

parameters:
  - description: SSH private key to authenticate the public key set in GitHub.
    displayName: SSH Private Key
    required: true
    name: KEBECHET_SSH_PRIVATE_KEY
  
  - description: GitHub OAuth token used for authentication.
    displayName: GitHub Oauth token
    required: true
    name: KEBECHET_TOKEN
