---
- name: Playbook to provision Thoth's Kebechet Bot deployment
    - openshift
    - thoth
    - kebechet
    - bot

  hosts: localhost
  vars:
    OCP_URL: "{{ lookup('env','OCP_URL') }}"
    OCP_TOKEN: "{{ lookup('env','OCP_TOKEN') }}"
    
    KEBECHET_APPLICATION_NAMESPACE: "{{ lookup('env','KEBECHET_APPLICATION_NAMESPACE') }}"
    KEBECHET_INFRA_NAMESPACE: "{{ lookup('env','KEBECHET_INFRA_NAMESPACE') }}"

  gather_facts: false
  connection: local
  roles:
  - role: thoth-ssh-key-check
  - role: thoth-kebechet-imagestreams
  - role: thoth-kebechet-bot
